# Generated by Django 5.2.4 on 2026-09-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0034_alter_feedreview_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='u_password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
